# Generated by Django 3.2 on 2021-04-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scaffoldapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='categorie',
        ),
        migrations.AddField(
            model_name='card',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie_cards', to='scaffoldapp.categorie'),
        ),
        migrations.AddField(
            model_name='image',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_images', to='scaffoldapp.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='icone',
            field=models.FileField(upload_to='card'),
        ),
        migrations.AlterField(
            model_name='image',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pack',
            name='couleur',
            field=models.TextField(default='#009cea'),
        ),
        migrations.AlterField(
            model_name='team',
            name='poste',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(),
        ),
    ]
