# Generated by Django 3.2 on 2021-05-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaffoldapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
