# Generated by Django 3.2 on 2021-05-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaffoldapp', '0002_delete_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
