# Generated by Django 3.2 on 2021-05-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaffoldapp', '0003_auto_20210503_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avantage',
            name='pack_avantage',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='Prestation',
        ),
        migrations.DeleteModel(
            name='Avantage',
        ),
    ]
